# Generated by Django 3.1.2 on 2020-11-21 05:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='场馆类型')),
                ('name', models.CharField(max_length=32, null=True)),
                ('price', models.IntegerField()),
                ('openState', models.BooleanField()),
                ('floor', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('startTime', models.CharField(max_length=10)),
                ('endTime', models.CharField(max_length=10)),
                ('openState', models.BooleanField()),
                ('accessible', models.BooleanField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.court')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('information', models.CharField(max_length=300)),
                ('openingHours', models.CharField(max_length=50, verbose_name='开放时间')),
                ('openTime', models.CharField(max_length=32)),
                ('closeTime', models.CharField(max_length=32)),
                ('contact', models.CharField(max_length=32, null=True)),
                ('openState', models.BooleanField()),
                ('foreDays', models.IntegerField()),
                ('durations', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(max_length=50, null=True)),
                ('loginToken', models.CharField(max_length=100, null=True)),
                ('loginTime', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('userId', models.IntegerField(null=True, unique=True, verbose_name='学生编号')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='StadiumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/stadium')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('S', 'success'), ('F', 'fail'), ('W', 'waiting')], default='W', max_length=2, verbose_name='预定结果')),
                ('startTime', models.CharField(max_length=50)),
                ('endTime', models.CharField(max_length=50)),
                ('payment', models.BooleanField(null=True, verbose_name='是否支付')),
                ('cancel', models.BooleanField(null=True, verbose_name='是否取消')),
                ('checked', models.BooleanField(null=True, verbose_name='是否使用')),
                ('leave', models.BooleanField(null=True, verbose_name='是否离开')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.court')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.duration')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stadium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('userId', models.IntegerField(unique=True, verbose_name='管理员编号')),
                ('email', models.EmailField(max_length=254)),
                ('loginToken', models.CharField(max_length=100, null=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stadium')),
            ],
        ),
        migrations.AddField(
            model_name='duration',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stadium'),
        ),
        migrations.AddField(
            model_name='duration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user'),
        ),
        migrations.AddField(
            model_name='court',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stadium'),
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%Y/%m/%d')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.court'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='ChangeDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openingHours', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=32)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(default=1)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manager')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.CharField(max_length=32)),
                ('endTime', models.CharField(max_length=32)),
                ('date', models.CharField(max_length=32)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(default=2)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.court')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manager')),
            ],
        ),
    ]
