# Generated by Django 3.1.2 on 2020-12-11 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium_id', models.IntegerField()),
                ('reserve_id', models.IntegerField()),
                ('score', models.IntegerField(default=3)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='场馆类型')),
                ('name', models.CharField(max_length=32, null=True)),
                ('price', models.IntegerField()),
                ('openState', models.BooleanField()),
                ('floor', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('userId', models.IntegerField(unique=True, verbose_name='管理员编号')),
                ('email', models.EmailField(max_length=254)),
                ('loginToken', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='manager', verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('open', models.BooleanField(default=True, verbose_name='会话状态')),
                ('checked', models.BooleanField(default=False, verbose_name='审核状态')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pinyin', models.CharField(max_length=100, null=True)),
                ('information', models.CharField(max_length=300)),
                ('openTime', models.CharField(max_length=32)),
                ('closeTime', models.CharField(max_length=32)),
                ('contact', models.CharField(max_length=32, null=True)),
                ('openState', models.BooleanField()),
                ('foreDays', models.IntegerField()),
                ('durations', models.CharField(max_length=32, null=True)),
                ('location', models.CharField(default='学堂路', max_length=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginToken', models.CharField(max_length=100, null=True)),
                ('loginTime', models.DateTimeField(auto_now=True, null=True)),
                ('auth', models.BooleanField(default=False)),
                ('type', models.CharField(default='在校学生', max_length=10)),
                ('name', models.CharField(max_length=32, null=True)),
                ('nickName', models.CharField(max_length=32, null=True)),
                ('userId', models.IntegerField(unique=True, verbose_name='学生编号')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='user', verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='StadiumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=30, null=True, verbose_name='图片描述')),
                ('image', models.ImageField(upload_to='stadium')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium', models.CharField(max_length=32)),
                ('court', models.CharField(max_length=32)),
                ('court_id', models.IntegerField()),
                ('duration_id', models.IntegerField()),
                ('result', models.CharField(choices=[('S', 'success'), ('F', 'fail'), ('W', 'waiting')], default='W', max_length=2, verbose_name='预定结果')),
                ('date', models.CharField(max_length=10)),
                ('startTime', models.CharField(max_length=50)),
                ('endTime', models.CharField(max_length=50)),
                ('payment', models.BooleanField(null=True, verbose_name='是否支付')),
                ('cancel', models.BooleanField(null=True, verbose_name='是否取消')),
                ('checked', models.BooleanField(null=True, verbose_name='是否使用')),
                ('leave', models.BooleanField(null=True, verbose_name='是否离开')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('U', 'user'), ('M', 'manager')], max_length=2, verbose_name='发送方')),
                ('manager_id', models.IntegerField(null=True)),
                ('content', models.CharField(max_length=500)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.session')),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('startTime', models.CharField(max_length=10)),
                ('endTime', models.CharField(max_length=10)),
                ('openState', models.BooleanField()),
                ('accessible', models.BooleanField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.court')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stadium')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='CourtType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openingHours', models.CharField(max_length=50, verbose_name='开放时间')),
                ('type', models.CharField(max_length=20, verbose_name='场馆类型')),
                ('duration', models.CharField(default='01:00', max_length=30, verbose_name='单次预约限定时长')),
                ('price', models.IntegerField(default=30, verbose_name='预约费用')),
                ('membership', models.IntegerField(default=3, verbose_name='同行人数')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stadium')),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='courtType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courttype'),
        ),
        migrations.AddField(
            model_name='court',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stadium'),
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comment')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.court'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='CollectEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stadium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openState', models.BooleanField()),
                ('openTime', models.CharField(max_length=30)),
                ('closeTime', models.CharField(max_length=30)),
                ('startDate', models.CharField(max_length=30)),
                ('foreDays', models.IntegerField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manager')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openingHours', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=32)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
                ('membership', models.IntegerField(default=1)),
                ('courtType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courttype')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manager')),
            ],
        ),
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.CharField(max_length=32)),
                ('endTime', models.CharField(max_length=32)),
                ('date', models.CharField(max_length=32)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(default=2)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.court')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manager')),
            ],
        ),
    ]
