# Generated by Django 3.1.2 on 2020-11-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stadium_foreday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='foreDay',
        ),
    ]
