# Generated by Django 3.1.2 on 2020-11-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment1',
        ),
    ]
