# Generated by Django 3.1.2 on 2020-11-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_comment1'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='img',
            field=models.ImageField(null=True, upload_to='img/%Y/%m/%d', verbose_name='场馆图片'),
        ),
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.CharField(max_length=20, verbose_name='场馆类型'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='userId',
            field=models.IntegerField(verbose_name='管理员编号'),
        ),
        migrations.AlterField(
            model_name='reserveevent',
            name='result',
            field=models.CharField(choices=[('S', 'success'), ('F', 'fail'), ('W', 'waiting')], default='W', max_length=2, verbose_name='预定结果'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='openingHours',
            field=models.CharField(max_length=50, verbose_name='开放时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.IntegerField(verbose_name='学生编号'),
        ),
    ]
