Page({
  // 图片资源
  data:{
    imgUrls:[
      getApp().globalData.imgUrl+'/res/instruction/instruction_home.jpg',
      getApp().globalData.imgUrl+'/res/instruction/instruction_detail.jpg',
      getApp().globalData.imgUrl+'/res/instruction/instruction_choose.jpg',
      getApp().globalData.imgUrl+'/res/instruction/instruction_verify.jpg',
      getApp().globalData.imgUrl+'/res/instruction/instruction_pay.png',
      getApp().globalData.imgUrl+'/res/instruction/instruction_user.jpg',
      getApp().globalData.imgUrl+'/res/instruction/instruction_mybook.jpg',
      getApp().globalData.imgUrl+'/res/instruction/instruction_ongoing.jpg',
      getApp().globalData.imgUrl+'/res/instruction/instruction_ongoingEvent.jpg',
      getApp().globalData.imgUrl+'/res/instruction/instruction_enable_notice1.jpg',
      getApp().globalData.imgUrl+'/res/instruction/instruction_enable_notice2.png',
      getApp().globalData.imgUrl+'/res/instruction/instruction_enable_notice3.png',
      getApp().globalData.imgUrl+'/res/instruction/instruction_notice.png',
    ],
    tutor_list:[
      {
        title:'简介',
        nodes:[{
          type:'text',
          value:'清动家园是一款运动场馆预定的小程序，目的在于帮助清华大学在校教职工快速预定校园内各种体育场馆。小程序的主要功能有：快速查找场馆，浏览场馆具体信息，场地查看与预定，在线支付预约费用，以及对场馆进行评论。' 
        }]
      },
      {
        title:'浏览场馆',
        nodes:[{
          type:'text',
          value:'在主页，您可以浏览所有的场馆，并通过左侧的选项框（1）筛选您感兴趣的运动项目，上方的筛选框（2）可以进一步筛选场馆和进行排序。最上方的搜索框（3）支持对场地名称和拼音的搜索。在找到希望查看的场馆后，点击相应区域（4）就可以查看场馆的详细信息了。'
        },
        {
          type:'img',
          value:getApp().globalData.imgUrl+'/res/instruction/instruction_home.jpg'
        }]
      },
      {
        title:'场馆具体信息',
        nodes:[{
          type:'text',
          value:'在场馆详情页，您可以查看场馆各项信息。点击场馆的距离信息（1）即可以查看场馆的位置与导航路线。点击左下角的收藏按钮（2）即可收藏或取消收藏该场馆，点击右下角的我要预约（3）即可进入预约界面。'
        },
        {
          type:'img',
          value:getApp().globalData.imgUrl+'/res/instruction/instruction_detail.jpg',
        }]
      },
      {
        title:'场地预约',
        nodes:[{
          type:'text',
          value:'在场地预约页，您可以查看场馆在未来几天内所有场地的预约状况，并选择选择自己希望预约的场地。在上方的运动项目区（1）选择运动项目，在左侧的日期选择区（2）选择要预约的日期，在右侧的时段选择区（3）选择可以预约的时段（灰色的时段表示不可预约）。您可以在一次预约中选择多个连续的时间段，但不可超过单次预约的上限。下方的提示栏（4）会提示您当前选择的预约时段是否符合预定要求。在选择完时段后，点击确认时间（5）即可进入下一步'
        },
        {
          type:'img',
          value:getApp().globalData.imgUrl+'/res/instruction/instruction_choose.jpg',
        },
        {
          type:'text',
          value:'点击确认时间按钮后，会弹出提示框让您对即将做出的预约进行再一次的确认，在您确认无误之后，请点击前往付款（1）按钮进入下一步。'
        },
        {
          type:'img',
          value:getApp().globalData.imgUrl+'/res/instruction/instruction_verify.jpg',
        },
        {
          type:'text',
          value:'在点击前往付款按钮之后，您需要在付款页面完成对场馆预定的支付。您可以选择三种支付方式（1）中的任意一种，接下来点击确认付款（3）并完成付款过程，到此为止，您已经完成了对场地的预定。'
        },
        {
          type:'img',
          value:getApp().globalData.imgUrl+'/res/instruction/instruction_pay.png',
        },]
      },
      {
        title:'预约信息查看',
        nodes:[{
          type:'text',
          value:'在“我的”页面，您可以查看自己已完成（1）和未完成（2）的预约'
        },
        {
          type:'img',
          value: getApp().globalData.imgUrl+'/res/instruction/instruction_user.jpg',
        },
        {
          type:'text',
          value:'在这两个页面中，你可以通过上方的筛选栏（1）筛选相应的预约，对于每个不同状态的预约，都有着对应的操作选项（2）。'
        },
        {
          type:'img',
          value:getApp().globalData.imgUrl+'/res/instruction/instruction_mybook.jpg',
        }]
      },
      {
        title:'签到和签退',
        nodes:[{
          type:'text',
          value:'如果有正在进行的预约，您应当及时地签到和签退，此时您可以在主页看到提示信息（1），点击之后可以查看当前正在进行的预约。'
        },
        {
          type:'img',
          value:getApp().globalData.imgUrl+'/res/instruction/instruction_ongoing.jpg',
        },
        {
          type:'text',
          value:'在当前预约界面中，您可以看到预定时间段（1）和当前剩余时间（2），您可以通过下方的按钮（3）进行签到和签退。'
        },
        {
          type:'img',
          value:getApp().globalData.imgUrl+'/res/instruction/instruction_ongoingEvent.jpg',
        }]
      },
      {
        title:'消息通知',
        nodes:[{
          type:'text',
          value:'为了方便收到预约信息变更的有关通知，我们强烈建议打开微信小程序的通知功能。具体方法如下：'
        },
        {
          type:'img',
          value:getApp().globalData.imgUrl+'/res/instruction/instruction_enable_notice1.jpg',
        },
        {
          type:'img',
          value:getApp().globalData.imgUrl+'/res/instruction/instruction_enable_notice2.png',
        },
        {
          type:'img',
          value:getApp().globalData.imgUrl+'/res/instruction/instruction_enable_notice3.png',
        },
        {
          type:'text',
          value:'完成上述操作后，您就可以在预约成功，取消，即将开始或结束时，在微信的服务通知中接收到我们发出的通知提醒。'
        },
        {
          type:'img',
          value:getApp().globalData.imgUrl+'/res/instruction/instruction_notice.png',
        },]
      },
    ]
  },

  onChangeTutor:function(e) {
    this.setData({activeName:e.detail})
  }
})